name: Auto Generate Configs and Deploy to Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # هر روز ساعت ۴ صبح به وقت UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Generate PAC and configs
        run: python scripts/generate_configs.py

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
